var cal = require("./calc.js")
console.log(cal.add(1,2))
console.log(cal.sub(1,2))
console.log(cal.mul(1,2))
console.log(cal.div(1,2))
console.log(cal.squ(2))
console.log(cal.max(1,2,3))
console.log(cal.maxv(1,2,3))
console.log(cal.min(1,2,3))
